export const states = [
  { slug: 'alabama', name: 'Alabama', stateTaxRate: 5, description: 'Alabama has state income tax, so take-home pay may be lower than in no-income-tax states.' },
  { slug: 'alaska', name: 'Alaska', stateTaxRate: 0, description: 'Alaska has no state income tax, which can help increase estimated take-home pay.' },
  { slug: 'arizona', name: 'Arizona', stateTaxRate: 2.5, description: 'Arizona has a flat state income tax rate for basic paycheck estimates.' },
  { slug: 'arkansas', name: 'Arkansas', stateTaxRate: 4.4, description: 'Arkansas has state income tax that may reduce take-home pay.' },
  { slug: 'california', name: 'California', stateTaxRate: 6, description: 'California has state income tax, so take-home pay may be lower than in states with no income tax.' },
  { slug: 'colorado', name: 'Colorado', stateTaxRate: 4.4, description: 'Colorado has a flat state income tax rate for wage income estimates.' },
  { slug: 'connecticut', name: 'Connecticut', stateTaxRate: 5, description: 'Connecticut has state income tax that can affect paycheck estimates.' },
  { slug: 'delaware', name: 'Delaware', stateTaxRate: 5.5, description: 'Delaware has state income tax that may reduce estimated take-home pay.' },
  { slug: 'florida', name: 'Florida', stateTaxRate: 0, description: 'Florida does not have a state income tax, so paycheck estimates mainly depend on federal payroll taxes and deductions.' },
  { slug: 'georgia', name: 'Georgia', stateTaxRate: 5.49, description: 'Georgia has state income tax that may affect take-home pay.' },
  { slug: 'hawaii', name: 'Hawaii', stateTaxRate: 7, description: 'Hawaii has state income tax, and actual results depend on income and filing details.' },
  { slug: 'idaho', name: 'Idaho', stateTaxRate: 5.8, description: 'Idaho has state income tax that can reduce net paycheck estimates.' },
  { slug: 'illinois', name: 'Illinois', stateTaxRate: 4.95, description: 'Illinois uses a flat state income tax rate, which can make basic paycheck estimates easier to understand.' },
  { slug: 'indiana', name: 'Indiana', stateTaxRate: 3.05, description: 'Indiana has state income tax, and some local taxes may also apply.' },
  { slug: 'iowa', name: 'Iowa', stateTaxRate: 4.4, description: 'Iowa has state income tax that can affect take-home pay.' },
  { slug: 'kansas', name: 'Kansas', stateTaxRate: 5.7, description: 'Kansas has state income tax that may reduce estimated net pay.' },
  { slug: 'kentucky', name: 'Kentucky', stateTaxRate: 4, description: 'Kentucky has state income tax that affects paycheck estimates.' },
  { slug: 'louisiana', name: 'Louisiana', stateTaxRate: 4.25, description: 'Louisiana has state income tax that can reduce take-home pay.' },
  { slug: 'maine', name: 'Maine', stateTaxRate: 6.75, description: 'Maine has state income tax and actual results depend on income and deductions.' },
  { slug: 'maryland', name: 'Maryland', stateTaxRate: 5.75, description: 'Maryland has state income tax, and local county taxes may also apply.' },
  { slug: 'massachusetts', name: 'Massachusetts', stateTaxRate: 5, description: 'Massachusetts has a flat state income tax rate for many wage estimates.' },
  { slug: 'michigan', name: 'Michigan', stateTaxRate: 4.25, description: 'Michigan has state income tax that may affect take-home pay.' },
  { slug: 'minnesota', name: 'Minnesota', stateTaxRate: 6.8, description: 'Minnesota has state income tax and actual withholding may vary by income.' },
  { slug: 'mississippi', name: 'Mississippi', stateTaxRate: 4.7, description: 'Mississippi has state income tax that can reduce estimated take-home pay.' },
  { slug: 'missouri', name: 'Missouri', stateTaxRate: 4.8, description: 'Missouri has state income tax that may affect paycheck estimates.' },
  { slug: 'montana', name: 'Montana', stateTaxRate: 5.9, description: 'Montana has state income tax that can reduce estimated net pay.' },
  { slug: 'nebraska', name: 'Nebraska', stateTaxRate: 5.84, description: 'Nebraska has state income tax and actual results may vary.' },
  { slug: 'nevada', name: 'Nevada', stateTaxRate: 0, description: 'Nevada has no state income tax, which can help increase take-home pay.' },
  { slug: 'new-hampshire', name: 'New Hampshire', stateTaxRate: 0, description: 'New Hampshire generally has no wage income tax for paycheck estimates.' },
  { slug: 'new-jersey', name: 'New Jersey', stateTaxRate: 5.5, description: 'New Jersey has state income tax that may reduce take-home pay.' },
  { slug: 'new-mexico', name: 'New Mexico', stateTaxRate: 4.9, description: 'New Mexico has state income tax that can affect net pay.' },
  { slug: 'new-york', name: 'New York', stateTaxRate: 5.5, description: 'New York has state income tax, and some local taxes may also apply depending on where you live or work.' },
  { slug: 'north-carolina', name: 'North Carolina', stateTaxRate: 4.5, description: 'North Carolina has a flat state income tax rate for basic paycheck estimates.' },
  { slug: 'north-dakota', name: 'North Dakota', stateTaxRate: 2.5, description: 'North Dakota has relatively low state income tax for many workers.' },
  { slug: 'ohio', name: 'Ohio', stateTaxRate: 3.5, description: 'Ohio has state income tax, and local taxes may also affect paychecks.' },
  { slug: 'oklahoma', name: 'Oklahoma', stateTaxRate: 4.75, description: 'Oklahoma has state income tax that can reduce take-home pay.' },
  { slug: 'oregon', name: 'Oregon', stateTaxRate: 8.75, description: 'Oregon has state income tax and no general sales tax, but paycheck estimates depend on income.' },
  { slug: 'pennsylvania', name: 'Pennsylvania', stateTaxRate: 3.07, description: 'Pennsylvania has a flat state income tax rate, but local taxes may also affect actual take-home pay.' },
  { slug: 'rhode-island', name: 'Rhode Island', stateTaxRate: 4.75, description: 'Rhode Island has state income tax that may affect net pay.' },
  { slug: 'south-carolina', name: 'South Carolina', stateTaxRate: 6.4, description: 'South Carolina has state income tax and actual results vary by income.' },
  { slug: 'south-dakota', name: 'South Dakota', stateTaxRate: 0, description: 'South Dakota has no state income tax, which can help increase estimated take-home pay.' },
  { slug: 'tennessee', name: 'Tennessee', stateTaxRate: 0, description: 'Tennessee has no state income tax on wages.' },
  { slug: 'texas', name: 'Texas', stateTaxRate: 0, description: 'Texas has no state income tax, which can make take-home pay higher compared with states that tax wages.' },
  { slug: 'utah', name: 'Utah', stateTaxRate: 4.65, description: 'Utah has a flat state income tax rate for basic paycheck estimates.' },
  { slug: 'vermont', name: 'Vermont', stateTaxRate: 6, description: 'Vermont has state income tax and actual withholding depends on income.' },
  { slug: 'virginia', name: 'Virginia', stateTaxRate: 5.75, description: 'Virginia has state income tax that can affect take-home pay.' },
  { slug: 'washington', name: 'Washington', stateTaxRate: 0, description: 'Washington has no state income tax on wages.' },
  { slug: 'west-virginia', name: 'West Virginia', stateTaxRate: 4.82, description: 'West Virginia has state income tax that may reduce estimated net pay.' },
  { slug: 'wisconsin', name: 'Wisconsin', stateTaxRate: 5.3, description: 'Wisconsin has state income tax that can affect paycheck estimates.' },
  { slug: 'wyoming', name: 'Wyoming', stateTaxRate: 0, description: 'Wyoming has no state income tax, which can help increase estimated take-home pay.' },
];